name: resolve-bot pre-commit

# Won't run on develop/main directly
on: [pull_request]

jobs:
  pre-commit:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
        ref: ${{ github.event.pull_request.head.ref }}
    - uses: actions/setup-python@v5.4.0
    - uses: pre-commit/action@v3.0.1
    #- uses: EndBug/add-and-commit@v9.1.4
    #  # Only need to try and commit if the action failed
    #  if: failure()
    #  with:
    #    fetch: false
    #    committer_name: GitHub Actions
    #    committer_email: actions@github.com
    #    message: Apply pre-commmit fixes 
